### ISSUE TITLE
Can not open file

### ISSUE THREAD

**Issue by sagudev** [nptr/msstyleEditor#10]
When I open file nothing is shown. I tried V 1.3.0.0 - beta2 and V 1.2.3.0
![slika](https://user-images.githubusercontent.com/16504129/40572771-9eb81200-60b5-11e8-8ba1-1c164b9dd778.png)

**Comment by sagudev** [comment]
No, https://smileylightspeed.deviantart.com/art/Luna-Plastic-Beta-80500430

**Comment by nptr** [comment]
Oh, thats a visual style for Windows XP! I don't support those, see the description on the main page!
They are however quite easy to modify since its more or less plaintext. Just use a PE resource tool, like ["Resource Hacker"](http://www.angusj.com/resourcehacker/) and export/modify/replace whatever you like.

**Comment by JustReadThis** [comment]
When Win XP still popular(win 8 not yet released), I used TGTSoft Stylebuilder + PE Resource tool, like ResHack or PE Explorer. Win XP kinda easy to modify rather than other win.
I think there is tutorial and tool around the internet that can guide you.
Good luck.

**Comment by sagudev** [comment]
I successfully used ResHack. But still it will be good to suport Windows XP styles too.
