### ISSUE TITLE
How do I change the scrollbars color? Which class/property do I need to change?

### ISSUE THREAD

**Issue by ericgl** [nptr/msstyleEditor#112]
*Windows Version*: <<Win11 22H2 en-US x64>>

**Question**
How do I change the scrollbars color? Which class/property do I need to change?

**Things you already tried**
The default scrollbar color in Win11 dark mode is 95, 95, 95 (Gray) over 17, 17, 17 (dark gray, very close to black).
I tried changing it by editing a copy of aero.msstyles.

**Additional context**
I'm using Win11 22H2 en-US x64 in dark mode.
I copied the default **aero.msstyles** and its **MUI** to a temporary folder to mess around with it.
I tried several options which mentioned the word "scrollbar", but I'm not sure which one is the correct option.

I also searched for "**95, 95, 95**" which is the default color of the scrollbar in dark mode - Only one match found (BORDERCOLOR in THUMBNAILBORDER). So I changed it to a different color, and clicked "Test" to see what this would change, but I don't see anything happening. But anyway it's probably not the correct property I need.

Microsoft could be using a bitmap with the gray color, but I can't find it.
Any help will be much appreciated.

**Checklist**
- My uxtheme.dll is NOT patched
- I am using the latest version of msstyleEditor (2.0.0.5)
- I DID NOT check the Wiki
- None of the other issues cover this

**Comment by nptr** [comment]
Hello, I appreciate you detailing the question. That makes things easier.

The thing is, I don't really know for fact which properties and images affect which UI element. I too can only guess, because I haven't edited a theme in a long time and that usually were minor changes. You seem to know your way around msstyles well enough, so my guesses might not help a lot:

- Checking the bitmap files in `DarkMode_Explorer::ScrollBar` and `ScrollBar` is what I'd do. I had success with that (altough not on Win11): https://github.com/nptr/msstyleEditor/issues/81#issuecomment-1122836811
- The bitmap could be very small and not visible in the image view. Check the image size in the status bars lower left corner.
- Be aware that there might be multiple images, one for each DPI setting! Make sure the change all or at least the one you are currently using.
- Don't trust the "Test" feature too much. It seems not all changes are applied cleanly. At least for me, the result is quite buggy. Not much I can do unfortunately. I suggest applying the theme via Windows means or from SecureUxTheme and double check the result.
- I assume with "My uxtheme.dll is NOT patched" you mean not patched on the drive but in memory instead? Or did I miss some news?

I hope I could help.

**Comment by ericgl** [comment]
Thanks for the reply.

I have checked the bitmaps THUMBBTNHORZ (953) and THUMBBTNVERT (954). 
I exported them, changed the color and re-imported them. Applied the theme, but it didn't make any change to the scrollbars color.

"My uxtheme.dll is NOT patched" - I mean it's not patched at all. Would patching it make any difference on Win11?
I was hoping I could simply apply the modified theme (with the modified msstyles) and it would get applied properly.

Currently, the only thing that I can see to natively change the scrollbars' colors is applying one of the built-in "Contrast themes".
So, no dice so far.

**Comment by nptr** [comment]
You absolutely have to patch uxtheme! Microsoft locks out third party themes. Didn't the "Test" feature complain that it couldn't apply the theme?

Please see msstyleEditors [README](https://github.com/nptr/msstyleEditor) for the tools you can (or have to) use in order to circumvent that barrier.

**Comment by ericgl** [comment]
**It worked!**
I used UXpatcher to patch a Win10 machine in dark mode.
Edited the .mstsyles and .theme files.
Put both in C:\Windows\Resources\Themes\
Applied via the GUI (Settings > Personalization > Theme)...and voila!
Check out this screenshot with the blue scrollbars: https://imgur.com/a/MWBIF4X
