### ISSUE TITLE
How to change title bar font anti-aliasing?

### ISSUE THREAD

**Issue by matoi974** [nptr/msstyleEditor#113]
*Windows Version*: Windows 7 and Windows 10 21H2

**Question**
I'm trying to change the Windows title bar font anti-aliasing to greyscale or no anti-aliasing, and hopefully customize the font family and size too.

**Things you already tried**
Tried poking around msstyleEditor on Windows 10, changing things at random and hoping to find the correct setting. Either I haven't found the correct setting, or the Test button doesn't reflect the changes I'm making (but other changes do seem to apply, I was able to customize a few colors here and there)

**Additional context**

* name or link to the theme in question
Currently using Penumbra10ws https://www.deviantart.com/scope10/art/Penumbra-10-Windows-10-visual-style-568740374 
* screenshot of the UI element you are referring to
![image](https://user-images.githubusercontent.com/63289008/227979971-7d5ab273-083e-4a41-a99f-91707cc430f1.png)
* depiction of the desired outcome
I want greyscale antialiasing or no antialiasing for the title bar, like Windows XP or Windows 11.

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor
- [x] I checked the Wiki
- [x] None of the other issues cover this

**Comment by nptr** [comment]
The font might be the `CAPTIONFONT` property in `CompositedWindow::Window`. At least their [example code](https://learn.microsoft.com/en-us/windows/win32/dwm/customframe#appendix-b-painting-the-caption-title) about custom window frames suggests that.

The font property also specifies the AA quality I think. msstyleEditor can only select from the font list in the PE resources however. So in order to select something unusual you probably need to use a resource hacking tool and change some font entries altogether (remove the Quality: Cleartype partaybe?). Then select the font from within msstyleEditor.

That's my guess at least. The details are for you to figure out.
