### ISSUE TITLE
Any way to add new class, Part and State

### ISSUE THREAD

**Issue by flarens** [nptr/msstyleEditor#127]
*Windows Version*: Win 10 22H2

**Question**
In new versions of Windows, the color of the side panel of the conductor was moved to the new ExplorerNavPane class.
Is there any way to add this new class?
The msstyleEditor program does not at all have tools for adding a class, only adding a Property.

**Things you already tried**
I managed to add a class through the Windows Style Builder program, but it cannot add the internal structures "Part 0" and "State 0", so the msstyleEditor does not add a parameter with the "Select a state or property first" error.
How to create the necessary structure in any way?

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor
- [x] I checked the Wiki
- [x] None of the other issues cover this

**Comment by nptr** [comment]
I think that might be a bug / edge case that I did not account for. I can make it so that Part 0 & State 0 always appear. Stay tuned.
In the meanwhile, you can try adding a property in WSB to ExplorerNavPane. Then Part 0 / State 0 might appear in msstyleEditor too.

Allowing to dynamically add classes in msstyleEditor is a task for another time.

**Comment by flarens** [comment]
Thank you. I managed to add the necessary values through the WSB program. I don’t know how this happened, but I did not notice the “Add Property” button.
