### ISSUE TITLE
change system font at once

### ISSUE THREAD

**Issue by geextahslex** [nptr/msstyleEditor#139]
Hi, I would like to change my system font. I want to know if there is a possibility to change all font entries at once instead of going through every section one by one.

Thank you :)

**Comment by nptr** [comment]
You could just replace the `font entry` in the font table, keeping the resource ids the same as before. Since the `font properties` refer to the actual font via the resource id, no change to the properties is needed. This can not be done with msstyleEditor. Use some resource hacker tool instead. I hope the following screenshot helps:

![grafik](https://github.com/nptr/msstyleEditor/assets/5485569/acfb6dd0-4e29-43f2-ae81-ee76732dfc2b)

Of course the new font should be chosen such that they approximately match the sizes and style of the old font. Because there is a reason why entry `502` is smaller than `503`. Presumably `502` is used for labels etc while `503` might be used for headers and title text. Just an example, inspect your the `font properties` with msstyleEditor to get a rough idea where they are used.

`font` or `font entry` ->the stuff you see in resource hacker. The actual font definition with resource id.
`font properties` -> the `FONT` properties in msstyleEditor. Those just refer to the `font entries`.
