### ISSUE TITLE
ReactOS and Windows XP and Server 2003 msstyle files support?

### ISSUE THREAD

**Issue by C4rl0b** [nptr/msstyleEditor#20]
Why Windows XP/Server 2003 .msstyle files are unsupported?

For doing new msstyles for ReactOS this unique Open Source tool it is useless.
And when opening ReactOS Lautus msstyle (you can decompress ReactOS LiveCD iso), the program just close.

**Comment by nptr** [comment]
There are two, completely different, style formats. Windows XP and thus ReactOS use the old format.
Windows Vista and on use the new format. Both formats share the same file extension.

* The old .msstyles are easily human editable because its just a resource dll that contains bitmaps and plaintext style descriptions.
* The new format is also a resource dll, but in contrast, the style description (color, positions etc.) are in an
undocumented binary format.

You are using the old format, so you can just open your .msstyle files with a PE resource editor and easily edit it without much previous knowledge. I also think there are tools that support XP styles, i bet even free ones; haven't researched tho.

For the new format, my tool is there to help. Supporting the old format was never intended and 
won't happen unless someone decides to do a PR. You are however right with that i should at least open
a dialog box explaining that the old format is not supported instead of just exiting/crashing the program.

**Comment by C4rl0b** [comment]
Could anyone do a Pull Request in order to supporting the Windows XP .msstyle format, please?
I tryied to do pull request but I am not familiar with Github pull request process...

**Comment by nptr** [comment]
Version 1.4.0.0 now displays a stronger and more detailed error message when a file
won't load. With that being done, I am now closing this issue because "won't fix".
