### ISSUE TITLE
Windows 10 Defender claiming Trojan:Win32/Fuery.B!cl detected

### ISSUE THREAD

**Issue by yountmg** [nptr/msstyleEditor#22]
Windows 10 Defender prevents download of msstyleEditorX64.zip with the following message.

"Failed - Virus detected.

From Event Log ->Name: Trojan:Win32/Fuery.B!cl

Trojan:Win32/Fuery.B!cl occasionally connects to a remote host to execute tasks like the following:

Notify attacker on the new infection
Sends gathered data from the infected computer
Download and execute additional files including an updated version of the trojan
Accept command from a remote attacker

**Comment by nptr** [comment]
I checked my uploads again, nothing was compromised so its Windows Defender failing again. See Issue #5 for example. They are not related though because i stopped using UPX compression a while ago and never had a compressed x64 release.

Scan [from VirusTotal](https://www.virustotal.com/#/file/61963a56f84cc377fd28c03dfe87cd8ae8721b2527ead719f2c0c4ac4408f07b) of the latest x64 version is fine for example.
