### ISSUE TITLE
Resizing bug: no scrolling or window scaling

### ISSUE THREAD

**Issue by SigmaTel71** [nptr/msstyleEditor#26]
![image](https://user-images.githubusercontent.com/17989678/53303678-9ba7a200-387e-11e9-928f-abb0a6ae0574.png)
Look on the "Common" part. You can see that variables' names are cutted off. If I try to expand them, no scrollbars appear.
![image](https://user-images.githubusercontent.com/17989678/53303708-d3aee500-387e-11e9-9e67-f9bf9421782b.png)

**Comment by PraetorAngel** [comment]
I have a similar issue. I cannot resize the three sections of the program. When I use the msstyles editor, I get a huge gap in the middle, and the left-hand tree and the right hand drop downs are almost unreadable. See attached picture. 
<img width="1920" alt="msstyles" src="https://user-images.githubusercontent.com/51677755/59236327-e55c9400-8bb2-11e9-90c1-e8ae8ad0dc59.png">
 My laptop resolution is 2160*3840 ish

**Comment by nptr** [comment]
I believe earlier versions were sizeable but I removed it along the way
because I didn't like the way the split panels interacted. Sorry for that. 

Anyways, check out [V 1.4.0.3](https://github.com/nptr/msstyleEditor/releases/tag/1.4.0.3). I introduced sizeable and movable panels.
This should satisfy most needs for a sizeable UI :)

**Comment by SigmaTel71** [comment]
> This should satisfy most needs for a sizeable UI :)

This looks very nice! Thanks! I'll close this issue, since it's resolved.
