### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by Mugen86** [nptr/msstyleEditor#31]
Hi, I would like to associate msstyleEditor with *.msstyles files.
But currently command line seems to be ignored or I do it wrong?

msstyleEditorX64.exe "C:\Windows\Resources\Themes\aero\aero.msstyles"

Does not load the aero.msstyles.

**Comment by nptr** [comment]
Command line arguments are ignored at the moment. Omission on my part.
But since its an easy task I just released a new version:  [V 1.4.0.4](https://github.com/nptr/msstyleEditor/releases/tag/1.4.0.4)

If the first command line argument is an existing file, msstyleEditor will try to load it.
Note that the file doesn't necessarily has to have the *.msstyles extension.

If its not a valid file visual style, a message box will pop up.
If its not even an existing file, the editor window will show up empty - as usually.

**Comment by nptr** [comment]
In case, for future reference:

The msstyleEditor doesn't register the *.msstyles extension because it is supposed to 
be portable. I expect the average user will download the editor, work with it a bit, and 
eventually throw it away again. An installer, which would be necessary for registering
for the extension, would just be an unnecessary obstacle. Also creating and maintaining
one is not really of interest for me.

**Comment by Mugen86** [comment]
Thanks a lot.
This makes it easier for me work with different msstyles.

Keep up the great work :)
