### ISSUE TITLE
Issues on Windows 10 1903

### ISSUE THREAD

**Issue by Kelode** [nptr/msstyleEditor#35]

**Comment by nptr** [comment]
What did you do, what was the expected behavior and what was the actual behaviour?

A difference in file size is normal and doesn't say much. Its the resource entries that count. I also doubt that there is a new format. Still, for some time now styles stop working and i know about it. I think it came with 1803 or 1809. Haven't found a solution yet and haven't invested much time.sry
I don't think its the .msstyles file itself, but Microsoft having changed sth or even actively refusing it.

You can send me a copy of the unmodified aero.msstyles and i'll look into it (don't have Win10 installed). Maybe there is indeed something new, but i doubt it.

**Comment by Kelode** [comment]
[aero.zip](https://github.com/nptr/msstyleEditor/files/3795422/aero.zip)
[aero.msstyles.zip](https://github.com/nptr/msstyleEditor/files/3795423/aero.msstyles.zip)

**Comment by Kelode** [comment]
Here, the 2 natives and original files which causes the problem. Trying to get aero.msstyles and save it without any change cause windows to reinitiate the original file. To be sure, I've put the file in a new folder before.

**Comment by nptr** [comment]
I have looked at the original style and output from the editor. The resource entries are exactly the same. For earlier Windows versions this was fine. As i suspected its probably because Microsoft changed
the requirements a style must fulfill in order to be accepted. No solution available at the moment...

**Comment by Kelode** [comment]
Ok, please stay in touch to the solution you could find for this purpose.. Have a nice day

**Comment by nptr** [comment]
I think version [1.5.0.0](https://github.com/nptr/msstyleEditor/releases/tag/1.5.0.0) fixes the issue. One reason was the missing signature at the end of the file. See issue #29 for details.

For those wondering how I cam to say "exactly the same" a few posts before, that was because I only compared the VARIANT/NORMAL section and not the whole file. The files as a whole usually differs a lot and since this was no issue before I never suspected what now it does matter. (Not all the differences, only the appended signature)
