### ISSUE TITLE
Is it possible to add a new property state?

### ISSUE THREAD

**Issue by puretrance** [nptr/msstyleEditor#40]
Is it possible to add a new property state?
ComboBox Border has Focused state, but ComboBox ReadOnly does not have Focused state.
If you switch to classic theme (Windows 7), you can see, that ComboBox ReadOnly can be focused.
On Aero themes, Focused state is missing, so you can't determine, is it focused or not.
If this property is missing, is it possible to add it? Not possible in the interface, you need repack all styles and add new.

If it is not clear, ComboBox can be one of two types: editable and read-only. When you set focus on editable ComboBox, cursor is showing, and all text is selected. When you set focus on read-only ComboBox , in Classic theme you see all text is selected (and non-editable), but in Aero theme, you see nothing (when mouse cursor NOT pointing over it).

So, this state is missing, but may be it is supported, and, if added manually, it may work.

But this **state** (not property) can't be added through the interface, so it is needed to extract all classes, add another, and pack it again.

**Comment by nptr** [comment]
Hello,

msstyleEditor is exposing all states known. I even double checked with Microsofts header files as well as the debug symbols. There is no sign of a "focused" state for ComboBox > ReadOnly, sorry. Only "normal", "hot", "pressed" and "disabled". You also can't directly compare the classic "theme" and Aero visual styles. The classic theme is not based on visual styles and not rendered by the DWM. So it can very well be that there are differences, because they are fundamentally different.

I hope i understood everything correctly. Sorry that this is not the answer you hoped to receive.
