### ISSUE TITLE
How to use this editor to modify windows .msstyle file?

### ISSUE THREAD

**Issue by shangfire** [nptr/msstyleEditor#65]
I've downloaded the release exe file and does the following steps:
1.copy an origin .msstyle file(aero.msstyle) to the desktop
2.replace a group of imagefiles(TaskbarPearl::Pearlicon and TaskbarPearl::TABLETMODEPEARLICON)
3.save the modifyed file and copy it to a folder in aero.theme folder, name the folder and the new .mssytle file with the same name
4.copy a new .theme file, modify the value VisualStyles::Path to the new .msstyle file
5.double click the new .theme file
but nothing changed, both in win7 and win10, is there anything wrong within the upper steps?

**Comment by nptr** [comment]
So you are creating a modified .msstyles and a modified .theme, create a new folder in the Themes directory and apply the .theme file? This sound correct to me.

Try changing something different, like the PUSHBUTTON or CHECKBOX images and see if those are applied. It could be that Windows isn't using the pearl icon from the theme. In fact, Windows 7 doesn't have this class but uses an embedded resource from the explorer.exe. Maybe Windows 10 just has this class but doesn't use it all the time?

With that you should be able to narrow down the issue.

**Comment by shangfire** [comment]
I've tried another way to use this tool:
1.create a new folder in aero folder, copy an origin .msstyle file(aero.msstyle) in this folder, change the .msstyle file and the folder with same name.
2.copy an origin .theme file(aero.theme) in the aero folder, rename it with the new name and modify the value VisualStyles::Path with the new .msstyle file path.
3.double click the new .theme file to use.
so far so good, the theme is successly used. the new .msstyle file can't be deleted, windows will alert that the file is use, and the origin .msstyle file(aero.msstyle) can be deleted now.

4.switch to another theme.
4.copy the new .msstyle file to another place, open it with this editor, do nothing but save, copy it back to the  folder where it comes from
5.double click the new .theme file.
the new theme can not be used, windows will use a default theme instead of this. 

I've find that the new .msstyle file edited by editor(do nothing but open and save) is diffrent with its origin version in byte size and I've learned that windows msstyle file has signature check or something. but in the source code, I do found something about the signature handling, so I'm confused about this situation

**Comment by nptr** [comment]
Yes, the files can be of different size. This is not because of missing data, but because the API that I am using apparently orders the resource sections within the file differently. It should not be a problem. Anyhow, lets tackle this issue structured:

- Ensure you are using the [latest version of msstyleEditor, which is 1.5.0.0](https://github.com/nptr/msstyleEditor/releases/tag/1.5.0.0)
- Ensure you are using a theme patcher like UltraUXThemePatcher
- Ensure other themes like from deviantart work, while yours don't
- If there is a working third party theme, please send me a link to it
- Tell me if the "Theme" => Test" feature works for you, or if you are getting something like this![](https://user-images.githubusercontent.com/49295024/55597178-17f49700-5701-11e9-9da1-bdd7cb952311.png)
- Tell me the exact Windows Versions you are using. With Build Number etc.

That said, I know that lately msstyleEditor themes seem to not work anymore for a lot of people. At least the "Test" feature. I still have to get to the bottom of this. Sorry for the inconvenience.

**Comment by shangfire** [comment]
Alright, so the using of this tool is based on premise that the theme patcher is already installed.
After installation of the theme patcher, the editor do works on my computer.
Thank you for the patience to answer.

**Comment by nptr** [comment]
Yes it is, glad I could help. Looks like I don't mention it anywhere :S

Btw, the theme patcher is what disables Microsofts signature check. My tools just writes an invalid signature, because 
one has to be there.
