### ISSUE TITLE
It is possible to fork an WinUI3 Version as long as someone wants to?

### ISSUE THREAD

**Issue by Shomnipotence** [nptr/msstyleEditor#73]
This is open source software, which means that a forked version with a modern interface can be developed as long as one developer is willing and has enough energy. The only difficulty is the need for frequent updates to match the new features you develop

**Comment by nptr** [comment]
Absolutely. Personally I'd be hoping for features too and not mere UI changes ;)

**Comment by OrthodoxWindows** [comment]
For Shomnipotence 
Sorry, but I'm dubious about the interest of make a WinUI version, because WinUI is the heir of UWP. But UWP / Metro/ Fluent /WinUI are interfaces are interfaces that possess their own widget, and therefore do not take into account visual styles. I find a little contradictory to build a visual style editor with a graphic library that does not use its same visual styles.

**Comment by Shomnipotence** [comment]
> Absolutely. Personally I'd be hoping for features too and not mere UI changes ;)

I mean UI only, with Fluent Design
