### ISSUE TITLE
Handle common parts (ID 0) that have multiple states

### ISSUE THREAD

**Issue by lars-berger** [nptr/msstyleEditor#97]
*Windows Version*: Win11

**Expected behavior**

In `vsstyle.h` the parts of a class seem to be defined as enums with the name `${CLASS_NAME}PARTS`. But there's a few classes that have an enum with the name `${CLASS_NAME}STATES`. This seems to mean that the the common part (ID 0) actually has different states.

eg. `COMBOBOXSTYLE` part 0 can have the states: NORMAL, HOT, PRESSED, DISABLED. 

affected classes (derived classes might also be affected):

```
COMBOBOXSTYLE
HEADERSTYLE
SCROLLBARSTYLE
TOOLBARSTYLE
TRACKBARSTYLE
LINK
```

**Actual behavior**

**Additional context**

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor
- [x] None of the other issues cover this

----
I also wanted to reach out to ask you about something...

Been doing a bit of detective work to try to understand `.msstyles` files but there's something I absolutely can't figure out. So my understanding is that `vsstyle.h` and `vssym32.h` are supposed to be the source of truth for part and state IDs. However, there's quite a few classes that aren't mentioned in these header files that also have no base class in the BCMAP section.

Picked out a few classes to show what i mean:
```
ExplorerStatusBar
ListViewPopup
ProperTree
PreviewPane
CommandModule
TaskBand2
DWMWindow
Explorer::TreeView (doesn't seem to actually have TreeView as a base class?)
```

How'd you manage to find the names and IDs of the parts/states of these classes? Did you manually find out what their states/parts customized and then came up with a name?? I can't find mentions of the part/state names anywhere online or in any headers.

**Comment by nptr** [comment]
**About finding part/state/property names:**
1. `vsstyle.h` and `vssym32.h` are the base. But they are as you noticed incomplete. I think this is because theme support was abandoned and so developers don't really need to know much about the internal structure.

2. MSDN has some parts here: https://learn.microsoft.com/en-us/windows/win32/controls/parts-and-states
Its probably the same as in the headers. I can't remember.

3. A great source are the debug symbols of uxtheme.dll. They contain (or contained) much more information. You can get them with Visual Studio from Microsofts Symbol Server. [This tool](https://github.com/wbenny/pdbex) can then help to extract readable information from the PDBs.

4. At last, you can always experiment and derive/guess what a part means. And yes, some of them in msstyleEditor really were.

I hope this answers your question :)
