### ISSUE TITLE
Dark mode losta all msstyle files

### ISSUE THREAD

**Issue by etmdevelopeowner** [nptr/msstyleEditor#99]
*Windows Version*: <<W11 ...>>

Please help. All msstyle file if i open and edit, after save, set white mode (no dark) Dark is lost!  
How to remain dark mode the msstyle file?

**Expected behavior**
A description of what you expected to happen.

**Actual behavior**
A clear and concise description of what happened instead.

**Additional context**
Everything you think helps understanding the problem.
* link to the theme in question
* screenshots
* error messages and error codes

**Checklist**
- [x] My uxtheme.dll is patched
- [x] I am using the latest version of msstyleEditor
- [x] None of the other issues cover this

**Comment by nptr** [comment]
Please properly fill out the bug report form so i can better understand the problem.

**Comment by nptr** [comment]
I interpret the question such that Windows switches to "bright" mode upon changing visual style. You expectation is that it stays in dark mode, provided the visual style supports dark mode. I guess this is the normal behavior of Windows.

If the theme is set for testing from within msstyleEditor, i could probably reapply dark mode. Otherwise you'd be out of luck. Anyways, based on guesses I'll not do anything here at the moment. Feel free to provide additional info, then i can revisit this issue.
